### PR TITLE
Added new feature Text Summarizer

### PR DESCRIPTION
**Pull request by sho6000**
- **this feauture allows the user to summarize any content by the bot**

### CODE REVIEW

**Comment by SOME-1HING** [comment]
Cannot use gensim version (3.8.2) mentioned in the commit because of a lot of errors in summarize function.

**Comment by sho6000** [comment]
gensim doesnt support summarization instead i added spacy please review @SOME-1HING

**Comment by SOME-1HING** [comment]
I have reviewed and the code and have fixed few errors. I also have merged the pull request to the main branch after resolving any conflicts.

**Comment by SOME-1HING** [comment]
> gensim doesnt support summarization instead i added spacy please review @SOME-1HING

I have reviewed and the code and have fixed few errors. I also have merged the pull request to the main branch after resolving any conflicts.

**Review by SOME-1HING — COMMENTED** [review]
I have reviewed and the code and have fixed few errors. I also have resolved all the conflicts.

**Pull request merged**
